import { User } from './user';

export const USERS: User[] = [
  {
    id: 11,
    name: 'Dr Nice',
    avatar: '../assets/icon.png',
    bet: 10,
    rate: '2.2',
    prize: 0,
    isWin: false,
    isLose: false,
  },
  {
    id: 12, name: 'Narco', avatar: '../assets/icon.png', bet: 100, rate: '1.2', prize: 0,
    isWin: false,
    isLose: false,
  },
  {
    id: 13,
    name: 'Bombasto',
    avatar: '../assets/icon.png',
    bet: 100,
    rate: '1.2',
    prize: 0,
    isWin: false,
    isLose: false,
  },
  {
    id: 14,
    name: 'Celeritas',
    avatar: '../assets/icon.png',
    bet: 75,
    rate: '5.0',
    prize: 0,
    isWin: false,
    isLose: false,
  },
  {
    id: 15,
    name: 'Magneta',
    avatar: '../assets/icon.png',
    bet: 100,
    rate: '2.2',
    prize: 0,
    isWin: false,
    isLose: false,
  },
  {
    id: 16,
    name: 'RubberMan',
    avatar: '../assets/icon.png',
    bet: 140,
    rate: '1.2',
    prize: 0,
    isWin: false,
    isLose: false,
  },
  {
    id: 17, name: 'Dynama', avatar: '../assets/icon.png', bet: 100, rate: '3.0', prize: 0, isWin: false,
    isLose: false,
  },
  {
    id: 18, name: 'Dr IQ', avatar: '../assets/icon.png', bet: 100, rate: '1.2', prize: 0,
    isWin: false,
    isLose: false,
  },
  {
    id: 19, name: 'Magma', avatar: '../assets/icon.png', bet: 500, rate: '2.2', prize: 0,
    isWin: false,
    isLose: false,
  },
  {
    id: 20,
    name: 'Tornado',
    avatar: '../assets/icon.png',
    bet: 1000,
    rate: '4.0',
    prize: 0,
    isWin: false,
    isLose: false,
  },
];
